version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/1
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails server -b 0.0.0.0
      "

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  stripe-listener:
    image: stripe/stripe-cli
    command: listen --forward-to app:3000/checkout_status --api-key ${STRIPE_API_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  sidekiq:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: >
      bash -c "
        bundle exec sidekiq
      "

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

volumes:
  db_data:
  redis:
